import { ApiProperty } from "@nestjs/swagger";
import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from "typeorm";
import { User } from "./user.entity";

@Entity()
export class JobRole {
    @ApiProperty({
        description:
            "custom jobRole id generated by uuid module. It acts as a unique identifier in the DB"
    })
    @PrimaryGeneratedColumn("uuid")
    roleId: string;

    @ApiProperty({
        description: "Company Name"
    })
    @Column({ nullable: true })
    companyName: string;

    @ApiProperty({
        description: "Start Date (Month and Year)"
    })
    @Column({ nullable: true })
    startDate: string; // Store as a Date with day set to the 1st of the month

    @ApiProperty({
        description: "End Date (Month and Year)"
    })
    @Column({ nullable: true })
    endDate: string;

    @ApiProperty({
        description:
            "How many years has the user worked in that particular company"
    })
    @Column({ nullable: true })
    yearsOfEmployment: number;

    @ApiProperty({
        description: "achievements of the user"
    })
    @Column({ nullable: true, type: "longtext" })
    achievements: string;

    @ApiProperty({
        description: "responsibilities on that job role of the user"
    })
    @Column({ nullable: true, type: "longtext" })
    responsibilities: string;

    @ApiProperty({
        description: "Job Title"
    })
    @Column({ nullable: true })
    jobTitle: string;

    @ApiProperty({
        description: "Role"
    })
    @Column({ nullable: true })
    role: string;

    @ApiProperty({
        description: "Additional Details"
    })
    @Column({ type: "text", nullable: true })
    additionalDetails: string;

    @ApiProperty({
        description: "User ID"
    })
    @ManyToOne(() => User, (user) => user.jobRoles, {
        onDelete: "CASCADE",
        onUpdate: "CASCADE"
    })
    user: User;
}
