import { Column, Entity, PrimaryColumn } from "typeorm";
import { ApiProperty } from "@nestjs/swagger";

@Entity()
export class TempClient {
    @ApiProperty({
        description: "custom user id generated by uuid module"
    })
    @PrimaryColumn()
    userId: string;

    @ApiProperty({
        description: "first name of the user"
    })
    @Column({ nullable: true })
    firstName: string;

    @ApiProperty({
        description: "last name name of the user"
    })
    @Column({ nullable: true })
    lastName: string;

    @ApiProperty({
        description: "Phone no"
    })
    @Column({ nullable: true })
    phone: string;

    @ApiProperty({
        description: "Email address"
    })
    @Column({ nullable: true })
    email: string;

    @ApiProperty({
        description: "location"
    })
    @Column({ nullable: true })
    location: string;

    @ApiProperty({
        description: "postcode"
    })
    @Column({ nullable: true })
    postcode: string;

    @ApiProperty({
        description: "county"
    })
    @Column({ nullable: true })
    county: string;

    @ApiProperty({
        description: "town"
    })
    @Column({ nullable: true })
    town: string;

    @ApiProperty({
        description: "portfolio"
    })
    @Column({ nullable: true })
    portfolio: string;

    @ApiProperty({
        description: "profileSummary"
    })
    @Column({ nullable: true, type: "text" })
    profileSummary: string;

    @ApiProperty({
        description: "Profile Link"
    })
    @Column({ nullable: true })
    profileLink: string;

    // Work History -> jsonArrayString -> will be projects jsonArrayString too

    /*
      jobTitle,
      companyName,
      city,
      startDate,
      endDate,
      role,
      jobResponsibilities -> jsonArrayString
      achievements -> jsonArrayString
      projects -> jsonArrayString
     */

    @ApiProperty({
        description: "workHistory"
    })
    @Column({ type: "text", nullable: true })
    workHistory: string;

    /*
      degreeType,
      fieldOfStudy,
      institutionName,
      startDate,
      endDate
   */

    @ApiProperty({
        description: "educations"
    })
    @Column({ type: "text", nullable: true })
    educations: string;

    @ApiProperty({
        description: "trainings"
    })
    @Column({ type: "text", nullable: true })
    trainings: string;

    @ApiProperty({
        description: "certificates"
    })
    @Column({ type: "text", nullable: true })
    certificates: string;

    @ApiProperty({
        description: "volunteerings"
    })
    @Column({ type: "text", nullable: true })
    volunteerings: string;

    @ApiProperty({
        description: "publications"
    })
    @Column({ type: "text", nullable: true })
    publications: string;

    /*
    patentName,
    patentNumber,
    patentUrl,
    date,
    description
    */
    @ApiProperty({
        description: "patents"
    })
    @Column({ type: "text", nullable: true })
    patents: string;

    @ApiProperty({
        description: "projects"
    })
    @Column({ type: "text", nullable: true })
    projects: string;

    @ApiProperty({
        description: "memberships"
    })
    @Column({ type: "text", nullable: true })
    memberships: string;

    @ApiProperty({
        description: "awards"
    })
    @Column({ type: "text", nullable: true })
    awards: string;

    /*
      list of string -> [React,Angular]
     */

    @ApiProperty({
        description: "professionalSkills"
    })
    @Column({ type: "text", nullable: true })
    professionalSkills: string;

    @ApiProperty({
        description: "technicalSkills"
    })
    @Column({ type: "text", nullable: true })
    technicalSkills: string;

    @ApiProperty({
        description: "coverLetter"
    })
    @Column({ type: "text", nullable: true })
    coverLetter: string;

    @ApiProperty({
        description: "promptApiBrokenFields"
    })
    @Column({ type: "text", nullable: true })
    promptApiBrokenFields: string;
}
