import { ApiProperty } from "@nestjs/swagger";
import {
    Column,
    CreateDateColumn,
    Entity,
    OneToMany,
    OneToOne,
    PrimaryColumn,
    UpdateDateColumn
} from "typeorm";
import { Role, UserStatus } from "../enums";
import { JobRole } from "./jobRole.entity";
import { Valuator } from "src/valuator/entities/valuator.entity";
import { CVProfile } from "src/profile/entities/CVProfile.entity";
import { File } from "src/files/entities/file.entity";
import { Notification } from "../../../notifications/entites/notification.entity";
import { UserTicket } from "../../../ticket/entities/userTicket.entity";
import { ChatEntity } from "../../../websocket/chat.entity";

@Entity()
export class User {
    @ApiProperty({
        description: "custom user id generated by uuid module"
    })
    @PrimaryColumn()
    userId: string;

    @Column({
        default: false,
        nullable: true
    })
    isActive: boolean;

    @ApiProperty({
        description:
            "While signup, when user will verify the phone number with otp, then it will be true"
    })
    @Column({
        default: false
    })
    isPhoneActive: boolean;

    @ApiProperty({
        description:
            "While signup, when user will verify the email address with code, then it will be true"
    })
    @Column({
        default: false
    })
    isEmailActive: boolean;

    @ApiProperty({
        description: "first name of the user"
    })
    @Column({ default: "first name" })
    firstName: string;

    @ApiProperty({
        description: "last name name of the user"
    })
    @Column({ default: "" })
    lastName: string;

    @ApiProperty({
        description: "location"
    })
    @Column({ default: "" })
    location: string;

    @ApiProperty({
        description: "postcode"
    })
    @Column({ nullable: true })
    postcode: string;

    @ApiProperty({
        description: "email of the user"
    })
    @Column({
        nullable: true
    })
    email: string;

    // on change the email address, verification needed.
    @Column({
        default: true,
        nullable: true
    })
    isEmailVerified: boolean;

    @Column({
        nullable: true
    })
    tempEmail: string;

    // on change the email address, verification needed.
    @Column({
        default: true,
        nullable: true
    })
    isPhoneVerified: boolean;

    @Column({
        nullable: true
    })
    tempPhone: string;

    @ApiProperty({
        description: "phone number of the user"
    })
    @Column({
        nullable: true
    })
    phone: string;

    @ApiProperty({
        description: "hashed password"
    })
    @Column({
        nullable: true
    })
    password: string;

    @ApiProperty({
        description: "profile Image of user"
    })
    @Column({
        default: false
    })
    profileImageUrl: string;

    @ApiProperty({
        description: "if the user has uploaded cv or not"
    })
    @Column({
        default: false
    })
    hasUploadedCV: boolean;

    @ApiProperty({
        description: "Uploaded Cv Url"
    })
    @Column({
        nullable: true
    })
    cvUrl: string;

    @ApiProperty({
        description: "Cv processing status"
    })
    @Column({
        default: false
    })
    isCvProcessing: boolean;

    @ApiProperty({
        description: "Cv Valuator processing status"
    })
    @Column({
        default: false
    })
    isCvValuatorProcessing: boolean;

    // New Fields

    @ApiProperty({
        description: "LinkedIn Link"
    })
    @Column({
        nullable: true
    })
    linkedInLink: string;

    @ApiProperty({
        description: "Profile Link"
    })
    @Column({
        nullable: true
    })
    profileLink: string;

    @ApiProperty({
        description: "Job Target 1"
    })
    @Column({
        nullable: true
    })
    jobTarget1: string;

    @ApiProperty({
        description: "Job Sector"
    })
    @Column({
        nullable: true
    })
    jobSector: string;

    // JSON string. so we can later change it to an array by JSON PARSE
    @ApiProperty({
        description: "Education of the user"
    })
    @Column({
        nullable: true,
        type: "longtext"
    })
    education: string;

    // JSON string. so we can later change it to an array by JSON PARSE
    @ApiProperty({
        description: "technicalSkills"
    })
    @Column({
        nullable: true,
        type: "longtext"
    })
    technicalSkills: string;

    @ApiProperty({
        description: "professionalSkills"
    })
    @Column({
        nullable: true,
        type: "longtext"
    })
    professionalSkills: string;

    // todo: refactor this if needed into a career table.
    @ApiProperty({
        description: "Current Salary"
    })
    @Column({
        nullable: true
    })
    currentSalary: string;

    // todo: refactor this if needed into a career table.
    @ApiProperty({
        description: "target Salary"
    })
    @Column({
        nullable: true
    })
    targetSalary: string;

    // todo: refactor this if needed into a career table.
    @ApiProperty({
        description: "profile summary"
    })
    @Column({ type: "longtext", nullable: true })
    profileSummary: string;

    @ApiProperty({
        description: "Additional Notes"
    })
    @Column({
        nullable: true,
        type: "longtext"
    })
    additionalNotes: string;

    @OneToMany(() => JobRole, (jobRole) => jobRole.user)
    jobRoles: JobRole[];

    // extra information
    @ApiProperty({
        description: "Additional Notes"
    })
    @Column({
        nullable: true,
        type: "longtext"
    })
    extras: string;

    @ApiProperty({
        description: "Highest education of user"
    })
    @Column({
        nullable: true
    })
    highestEducation: string;

    @ApiProperty({
        description: "CVLib Signup Email of user"
    })
    @Column({
        nullable: true
    })
    cvLibEmail: string;

    @Column({ nullable: true, type: "bigint" })
    @ApiProperty({ description: "Cv Lib UserId" })
    cvLibUserId: number;

    @Column({ nullable: true, type: "bigint" })
    @ApiProperty({ description: "Reed UserId" })
    reedUserId: number;

    @ApiProperty({
        description: "Reed Signup Email of user"
    })
    @Column({
        nullable: true
    })
    reedEmail: string;

    @ApiProperty({
        description: "Customer ID of user in Stripe"
    })
    @Column({
        nullable: true
    })
    stripeCustomerId: string;

    @OneToOne(() => Valuator, (valuator) => valuator.user)
    valuator: Valuator;

    @OneToOne(() => CVProfile, (CVProfile) => CVProfile.user)
    cvProfile: CVProfile;

    @ApiProperty({
        description: "Cv Specialist Id"
    })
    @Column({
        nullable: true
    })
    cvSpecialistId: string;

    @OneToMany(() => File, (file) => file.user)
    files: File[];

    @Column({
        type: "enum",
        enum: UserStatus,
        default: UserStatus.Offline
    })
    status: UserStatus;

    @ApiProperty({
        description: "role of the user. could be user , or CV specialist"
    })
    @Column({
        default: Role.CLIENT
    })
    role: string;

    @ApiProperty({
        description: "chats sent by the user"
    })
    @OneToMany(() => ChatEntity, (chat) => chat.sender)
    chats: ChatEntity[];

    @OneToMany(() => UserTicket, (userTicket) => userTicket.user)
    tickets: UserTicket[];

    @OneToMany(() => Notification, (notification) => notification.user, {
        nullable: true
    })
    notifications: Notification[];

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;

    @Column({
        nullable: true
    })
    bookedAt: Date;

    @Column({
        nullable: true,
        type: "longtext"
    })
    basket: string;

    @Column({
        nullable: true,
        type: "longtext"
    })
    purchased: string;

    // Intra CRM columns

    @Column({
        nullable: true
    })
    salary: string;

    @Column({
        nullable: true
    })
    salesPerson: string;

    @Column({
        nullable: true,
        default: "Organic"
    })
    source: string;

    @Column({
        nullable: true
    })
    targetRole: string;

    @Column({
        nullable: true
    })
    sector: string;

    @Column({
        nullable: true
    })
    county: string;

    @Column({
        nullable: true
    })
    package: number;

    @Column({
        nullable: true
    })
    paymentType: string;

    @Column({
        nullable: true
    })
    services: string;

    @Column({
        nullable: true
    })
    referral: string;

    @Column({
        nullable: true
    })
    discount: string;

    @ApiProperty({
        description: "Predicted salary by valuator."
    })
    @Column({ nullable: true })
    valuatorSalary: string;

    @ApiProperty({
        description: "ATS Score According to user CV"
    })
    @Column({ nullable: true })
    keyWordScore: number;

    @ApiProperty({
        description: "Grammer Score According to user CV"
    })
    @Column({ nullable: true })
    grammerScore: number;
}
