import { ApiProperty } from "@nestjs/swagger";
import { User } from "src/auth/0auth2.0/entites/user.entity";
import { UploadType } from "src/files/enums";
import {
    Column,
    CreateDateColumn,
    Entity,
    JoinColumn,
    ManyToOne,
    PrimaryGeneratedColumn,
    UpdateDateColumn
} from "typeorm";
import { Role as UserRoles } from "src/auth/0auth2.0/enums";

@Entity()
export class CvMakerFile {
    @ApiProperty({
        description: "Custom id generated by uuid module"
    })
    @PrimaryGeneratedColumn("uuid")
    id: string;

    @ApiProperty({
        description: "File name"
    })
    @Column({ default: "" })
    name: string;

    @ApiProperty({
        description: "Mime type of the file"
    })
    @Column({ default: "" })
    mimeType: string;

    @ApiProperty({
        description: "Extension of the file"
    })
    @Column({ default: "" })
    fileExtension: string;

    @ApiProperty({
        description: "Path of the file"
    })
    @Column({ default: "" })
    path: string;

    @ApiProperty({
        description: "Purpose of the file being uploaded"
    })
    @Column({ type: "enum", enum: UploadType, default: UploadType.UPLOAD })
    uploadedType: UploadType;

    @ApiProperty({
        description: "Role of the user that uploaded the file"
    })
    @Column({ type: "enum", enum: UserRoles, default: UserRoles.ADMIN })
    uploadedBy: UserRoles;

    @ApiProperty({
        description: "User id"
    })
    @ManyToOne(() => User, (user) => user.files, {
        onDelete: "CASCADE"
    })
    @JoinColumn({ name: "userId" })
    user: User;

    @ApiProperty({
        description: "Timestamp for when the file was created"
    })
    @CreateDateColumn()
    createdAt: Date;

    @ApiProperty({
        description: "Timestamp for when the file was last updated"
    })
    @UpdateDateColumn()
    updatedAt: Date;
}
