import { ApiProperty } from "@nestjs/swagger";
import {
    Column,
    Entity,
    JoinColumn,
    ManyToOne,
    PrimaryGeneratedColumn
} from "typeorm";
import { Role as UserRoles } from "src/auth/0auth2.0/enums";
import { User } from "src/auth/0auth2.0/entites/user.entity";
import { UploadType } from "../enums";
import { ChatEntity } from "src/websocket/chat.entity";

@Entity()

/* The File Class represents file object containing info about the files uploaded by the users. */
export class File {
    @ApiProperty({
        description: "Custom id generated by uuid module"
    })
    @PrimaryGeneratedColumn("uuid")
    id: string;

    @ApiProperty({
        description: "File name"
    })
    @Column({ default: "" })
    name: string;

    @ApiProperty({
        description: "Is this file a cv or not"
    })
    @Column({ default: false })
    isCv: boolean;

    @ApiProperty({
        description: "Mime type of the file"
    })
    @Column({ default: "" })
    mimeType: string;

    @ApiProperty({
        description: "Extension of the file"
    })
    @Column({ default: "" })
    fileExtension: string;

    @ApiProperty({
        description: "Path of the file"
    })
    @Column({ default: "" })
    path: string;

    @ApiProperty({
        description: "Purpose of the file being uploaded"
    })
    @Column({ type: "enum", enum: UploadType, default: UploadType.UPLOAD })
    uploadedType: UploadType;

    @ApiProperty({
        description: "Role of the user that uploaded the file"
    })
    @Column({ type: "enum", enum: UserRoles, default: UserRoles.CLIENT })
    uploadedBy: UserRoles;

    @ApiProperty({
        description: "User id"
    })
    @ManyToOne(() => User, (user) => user.files, {
        onDelete: "CASCADE"
    })
    @JoinColumn({ name: "userId" })
    user: User;

    @ApiProperty({
        description: "Chat id"
    })
    @ManyToOne(() => ChatEntity, (chat) => chat.files, {
        onDelete: "CASCADE",
        nullable: true
    })
    chat: ChatEntity;
}
